<?php
require_once __DIR__ . '/../php/layout.php';
$user = requireProfile(['medico']);
$database = db(); $message = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verifyCsrf();
    try {
        $action = $_POST['action'] ?? ''; $attendanceId = (int) ($_POST['atendimento_id'] ?? 0);
        if ($action === 'start') {
            $appointmentId = (int) $_POST['agendamento_id']; $appointment = $database->prepare('SELECT cliente_id FROM agendamentos WHERE id = ?'); $appointment->execute([$appointmentId]); $appointment = $appointment->fetch();
            if (!$appointment) throw new InvalidArgumentException('Agendamento nao encontrado.');
            $database->prepare('INSERT INTO atendimentos (agendamento_id, cliente_id, medico_id) VALUES (?, ?, ?)')->execute([$appointmentId, $appointment['cliente_id'], $user['id']]); $database->prepare('UPDATE agendamentos SET medico_id = ?, status = ? WHERE id = ?')->execute([$user['id'], 'em_atendimento', $appointmentId]); $message = 'Atendimento iniciado.';
        } elseif ($action === 'diagnosis') { $database->prepare('UPDATE atendimentos SET diagnostico = ? WHERE id = ? AND medico_id = ?')->execute([trim($_POST['diagnostico']), $attendanceId, $user['id']]); $message = 'Diagnostico salvo.';
        } elseif ($action === 'exam') { $database->prepare('INSERT INTO exames_solicitados (atendimento_id, descricao, prioridade, observacao) VALUES (?, ?, ?, ?)')->execute([$attendanceId, trim($_POST['descricao']), $_POST['prioridade'], trim($_POST['observacao'] ?? '')]); $message = 'Exame solicitado.';
        } elseif ($action === 'prescription') { $database->prepare('INSERT INTO prescricoes (atendimento_id, medicamento, dose, frequencia, duracao, instrucoes) VALUES (?, ?, ?, ?, ?, ?)')->execute([$attendanceId, trim($_POST['medicamento']), trim($_POST['dose']), trim($_POST['frequencia']), trim($_POST['duracao']), trim($_POST['instrucoes'] ?? '')]); $message = 'Medicamento prescrito.';
        } elseif ($action === 'discharge') { $database->prepare("UPDATE atendimentos SET alta = ?, fim = CURRENT_TIMESTAMP, status = 'concluido' WHERE id = ? AND medico_id = ?")->execute([trim($_POST['alta']), $attendanceId, $user['id']]); $appointment = $database->prepare('SELECT agendamento_id FROM atendimentos WHERE id = ?'); $appointment->execute([$attendanceId]); $appointmentId = $appointment->fetchColumn(); if ($appointmentId) $database->prepare('UPDATE agendamentos SET status = ? WHERE id = ?')->execute(['concluida', $appointmentId]); $message = 'Alta registrada e consulta concluida.';
        } elseif ($action === 'admission') { $database->prepare('INSERT INTO internacoes (paciente_id, atendimento_id, leito, motivo, custo) SELECT cliente_id, id, ?, ?, ? FROM atendimentos WHERE id = ? AND medico_id = ?')->execute([trim($_POST['leito']), trim($_POST['motivo']), (float) $_POST['custo'], $attendanceId, $user['id']]); $message = 'Internacao registrada.';
        } elseif ($action === 'evolution') { $database->prepare('INSERT INTO evolucoes (internacao_id, profissional_id, texto) VALUES (?, ?, ?)')->execute([(int) $_POST['internacao_id'], $user['id'], trim($_POST['texto'])]); $message = 'Evolucao registrada.'; }
    } catch (Throwable $exception) { $message = 'Erro: ' . $exception->getMessage(); }
}
$appointments = $database->prepare("SELECT a.*, u.nome AS cliente FROM agendamentos a JOIN clientes c ON c.id = a.cliente_id JOIN usuarios u ON u.id = c.usuario_id WHERE a.status IN ('agendada','chegou','em_triagem','em_atendimento') ORDER BY a.inicio"); $appointments->execute(); $appointments = $appointments->fetchAll();
$attendances = $database->prepare('SELECT atd.*, u.nome AS cliente FROM atendimentos atd JOIN clientes c ON c.id = atd.cliente_id JOIN usuarios u ON u.id = c.usuario_id WHERE atd.medico_id = ? ORDER BY atd.inicio DESC'); $attendances->execute([$user['id']]); $attendances = $attendances->fetchAll();
$admissions = $database->query("SELECT i.*, u.nome AS paciente FROM internacoes i JOIN clientes c ON c.id = i.paciente_id JOIN usuarios u ON u.id = c.usuario_id WHERE i.status = 'aberta' ORDER BY i.entrada_em DESC")->fetchAll();
pageStart('Atendimento medico e internacao', $user); if ($message) echo '<p role="status">' . e($message) . '</p>';
echo '<h2>Proximos atendimentos</h2><table><tr><th>Cliente</th><th>Inicio</th><th>Especialidade</th><th>Acao</th></tr>'; foreach ($appointments as $item) echo '<tr><td>' . e($item['cliente']) . '</td><td>' . e($item['inicio']) . '</td><td>' . e($item['especialidade']) . '</td><td><form method="post"><input type="hidden" name="csrf" value="' . e(csrfToken()) . '"><input type="hidden" name="action" value="start"><input type="hidden" name="agendamento_id" value="' . e($item['id']) . '"><button type="submit">Iniciar</button></form></td></tr>'; echo '</table>';
echo '<h2>Prontuarios</h2>'; foreach ($attendances as $item) { echo '<section><h3>ID ' . e($item['id']) . ' - ' . e($item['cliente']) . '</h3><p>Diagnostico: ' . e($item['diagnostico'] ?: 'Nao registrado') . '</p><form method="post"><input type="hidden" name="csrf" value="' . e(csrfToken()) . '"><input type="hidden" name="atendimento_id" value="' . e($item['id']) . '"><label>Diagnostico: <textarea name="diagnostico" required></textarea></label><button name="action" value="diagnosis">Salvar</button></form><form method="post"><input type="hidden" name="csrf" value="' . e(csrfToken()) . '"><input type="hidden" name="atendimento_id" value="' . e($item['id']) . '"><input name="descricao" placeholder="Exame" required><select name="prioridade"><option>normal</option><option>urgente</option></select><input name="observacao" placeholder="Observacao"><button name="action" value="exam">Solicitar exame</button></form><form method="post"><input type="hidden" name="csrf" value="' . e(csrfToken()) . '"><input type="hidden" name="atendimento_id" value="' . e($item['id']) . '"><input name="medicamento" placeholder="Medicamento" required><input name="dose" placeholder="Dose" required><input name="frequencia" placeholder="Frequencia" required><input name="duracao" placeholder="Duracao" required><input name="instrucoes" placeholder="Instrucoes"><button name="action" value="prescription">Prescrever</button></form><form method="post"><input type="hidden" name="csrf" value="' . e(csrfToken()) . '"><input type="hidden" name="atendimento_id" value="' . e($item['id']) . '"><textarea name="alta" placeholder="Orientacoes de alta" required></textarea><button name="action" value="discharge">Dar alta e concluir</button></form><form method="post"><input type="hidden" name="csrf" value="' . e(csrfToken()) . '"><input type="hidden" name="atendimento_id" value="' . e($item['id']) . '"><input name="leito" placeholder="Leito" required><input name="motivo" placeholder="Motivo" required><input name="custo" type="number" step="0.01" min="0" placeholder="Custo" required><button name="action" value="admission">Encaminhar para internacao</button></form></section>'; }
echo '<h2>Internacoes abertas</h2><table><tr><th>Paciente</th><th>Leito</th><th>Entrada</th><th>Custo</th></tr>'; foreach ($admissions as $item) echo '<tr><td>' . e($item['paciente']) . '</td><td>' . e($item['leito']) . '</td><td>' . e($item['entrada_em']) . '</td><td>' . e($item['custo']) . '</td></tr>'; echo '</table>'; pageEnd();
